# Generated by Django 2.1.8 on 2019-05-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='similar_movie',
            field=models.ManyToManyField(blank=True, related_name='_movie_similar_movie_+', to='movies.Movie'),
        ),
    ]
